Feat/balaji
GlueOps/app-catalog pull request #1
Opened 2024-09-07 08:52 UTC by balajisa09

Adding app-catalog api server

2024-09-17 19:53 UTC, venkatamutyala commented on .gitignore
Could you use an official .gitignore?

https://github.com/github/gitignore/blob/main/Python.gitignore

2024-09-17 19:55 UTC, venkatamutyala submitted a review, later dismissed

2024-09-19 02:30 UTC, venkatamutyala commented
/help

2024-09-19 02:30 UTC, venkatamutyala commented
/analyze

2024-09-19 02:35 UTC, venkatamutyala commented on app/main.py
> +            "app_link": "argocd.{captain_domain}/applications/{namespace}/{app_name}".format(captain_domain=captain_domain, namespace=namespace, app_name=app_name),
@balajisa09 this looks like it would be a small change to keep things consistent with f-strings that you have used elsewhere.

2024-09-19 02:36 UTC, venkatamutyala submitted a review, later dismissed

2024-09-22 07:00 UTC, venkatamutyala requested changes
I think the load_kube_config is something that i added to the helpers library a while back. Can you take a quick look and see if it makes sense to use mine over yours?

2024-09-22 07:11 UTC, balajisa09 commented on app/main.py
> +def load_kube_config():
yeah we can reuse it here

2024-09-22 07:16 UTC, venkatamutyala approved these changes

2024-09-22 07:16 UTC, merged